---
- hosts: all
  become: yes

  tasks: 
    - name: Ensure Yum isupdated
      yum: name=* state=latest   

    - name: Install Remi repo
      yum: 
          name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm" 
          state: present

    - name: Import Remi GPG key
      rpm_key: 
          key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
          state: present

    - name: Install Epel Repo
      yum: 
        name: epel-release
        state: present

    - name: Ensure firewalld is stopped (for testing)
      service: name=firewalld state=stopped

    - name: Install Node.js and npm
      yum: name=npm state=present enablerepo=epel

    - name: Install Forver (to run our Node.js app)
      npm: name=forver global=yes state=present

