# ansible-playbook ansible/playbooks/nodejs-app-playbook.yml -i ansible/inventory/ansible_hosts --limit "*.2" --extra-vars="node_app_location=/usr/local/opt/node"
---
- hosts: all
  become: yes

  tasks: 
    - name: Ensure Yum isupdated
      yum: name=* state=latest   

    - name: Install Remi repo
      yum: 
          name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm" 
          state: present

    - name: Import Remi GPG key
      rpm_key: 
          key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
          state: present

    - name: Install Epel Repo
      yum: 
        name: epel-release
        state: present

    - name: Ensure firewalld is stopped (for testing)
      service: name=firewalld state=stopped

    - name: Install Node.js and npm
      yum: name=npm state=present enablerepo=epel

    - name: Install Forver (to run our Node.js app)
      npm: name=forever global=yes state=present

#
#
# COPY LOCAL NODE APP TO SERVER AAND INSTALL
#
    - name: Ensure Node.js app folder exists on sever
      file: path="{{ node_app_location }}" state=directory

    - name: Copy example node app to app server
      copy: "src=../../node-app dest={{ node_app_location }}"

    - name: Install app dependencis from package.json
      npm: path={{ node_app_location }}/node-app

#
#
# START NODE APP
    - name: Check list of runnig node.js apps
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start node-app
      command: "forever start {{ node_app_location }}/node-app/app.js"
      when: "forever_list.stdout.find(node_app_location + '/node-app/app.js') == -1"

